spring.application.name=EcoGet

spring.datasource.url=jdbc:postgresql://localhost:5432/eco_get_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

security.jwt.expiracao=30
security.jwt.chave-assinatura=ZWNvZ2V0LXNlY3JldC1rZXktcGFyYS1qd3QtYXV0aGVudGljYXRpb24=

logging.level.org.springframework.security=DEBUG
logging.level.com.example.EcoGet.security=DEBUG
